### ISSUE TITLE
ESP boards

### ISSUE THREAD

**Issue by SargonofAssyria** [Hoeby/ESP32-Doorbell#1]
It works perfect!
I want to use fixed SSID and password for the Wifi connection.
Is that possible?
Best Regards, Eddy

**Comment by Hoeby** [comment]
The wifi-manager will store your SSID and password for the wifi connection and keeps this as fixed credentials.
After reboot/restart these settings will be used, unless you have used the "clear wifi" button in the "ESP settings" menu.

In the standard code there is no default option to bypass the wifi-manager and place a default SSID and password.

**Comment by SargonofAssyria** [comment]
Ok.

**Comment by jvanderzande** [comment]
You free to hardcode it in the source as preference but I honestly do not see any benefit for that as it is a onetime thing to define initially and after that will always use the defined SSID unless it isn't available, at which time it will go into AP mode again. :)
